import { NOTE_NAMES_15, NOTE_NAMES_21 } from '../core/converter';

export interface EditorIntervals {
  default: number;
  short: number;
  long: number;
}

export interface EditorToken {
  notes: string[];
  interval: number;
  symbol: '-' | '~' | ',';
}

export interface ChordPlanItem {
  sourceNotes: string[];
  addedNotes: string[];
  chordName: string;
  symbol: '-' | '~' | ',';
}

let playbackContext: AudioContext | null = null;
let playbackTimers: number[] = [];

export function parseEditorScore(text: string, intervals: EditorIntervals): EditorToken[] {
  const clean = String(text)
    .replace(/【间隔】[\s\S]*?【勿删】/g, '')
    .replace(/\s+/g, '');
  const tokens: EditorToken[] = [];
  const pattern = /([a-g][4-6](?:&[a-g][4-6])*)([-~,]?)/gi;
  for (const match of clean.matchAll(pattern)) {
    const notes = String(match[1]).toLowerCase().split('&').filter((note) =>
      NOTE_NAMES_21.includes(note as (typeof NOTE_NAMES_21)[number])
    );
    if (!notes.length) continue;
    const symbol = normalizeSymbol(match[2]);
    tokens.push({
      notes: [...new Set(notes)],
      symbol,
      interval: symbol === '~' ? intervals.short : symbol === ',' ? intervals.long : intervals.default
    });
  }
  return tokens;
}

export function buildEditorScript(
  title: string,
  tokens: EditorToken[],
  use21Keys: boolean,
  pressTime = 35,
  template: 'default' | 'simple' | 'custom' = 'default',
  customTemplate = ''
): string {
  const names = use21Keys ? NOTE_NAMES_21 : NOTE_NAMES_15;
  const columns = use21Keys ? 7 : 5;
  const startX = use21Keys ? 410 : 780;
  const startY = use21Keys ? 980 : 215;
  const gap = use21Keys ? 270 : 195;
  const coordinates: Record<string, number[]> = {};
  names.forEach((name, index) => {
    coordinates[name] = [
      startX + (index % columns) * gap,
      startY + Math.floor(index / columns) * (use21Keys ? -110 : 195)
    ];
  });
  const rows = tokens.map((token) => ({
    keys: token.notes,
    sleep: token.interval
  }));
  const values: Record<string, string> = {
    title: safeTitle(title),
    coordsJson: JSON.stringify(coordinates, null, 2),
    pressTime: String(Math.max(10, Math.min(300, Math.round(pressTime)))),
    scoreJson: JSON.stringify(rows, null, 2)
  };
  if (template === 'custom') {
    if (!customTemplate.includes('{{scoreJson}}')) {
      throw new Error('自定义模板必须包含 {{scoreJson}}');
    }
    return customTemplate.replace(/\{\{(title|coordsJson|pressTime|scoreJson)\}\}/g, (_, key: string) =>
      values[key] ?? ''
    );
  }
  if (template === 'simple') {
    return [
      `// ${values.title} - generated by SkyForce`,
      'auto.waitFor();',
      `var keyMap = ${values.coordsJson};`,
      `var pressTime = ${values.pressTime};`,
      `var score = ${values.scoreJson};`,
      'score.forEach(function(item){',
      '  item.keys.forEach(function(key){var p=keyMap[key];if(p)press(p[0],p[1],pressTime);});',
      '  sleep(item.sleep);',
      '});',
      ''
    ].join('\n');
  }
  return [
    `// ${values.title} - generated by SkyForce`,
    'auto.waitFor();',
    `var keyMap = ${values.coordsJson};`,
    `var pressTime = ${values.pressTime};`,
    'var playbackSpeed = 1;',
    'var paused = false;',
    `var time=${Math.max(1, Math.round(Math.min(...tokens.map((token) => token.interval))))};`,
    `var score = ${values.scoreJson};`,
    '',
    'function waitWhilePaused(){while(paused)sleep(100);}',
    'function togglePause(){paused=!paused;toast(paused?"Paused":"Playing");}',
    'function setPlaybackSpeed(speed){playbackSpeed=Math.max(0.25,speed);}',
    'score.forEach(function(item){',
    '  waitWhilePaused();',
    '  item.keys.forEach(function(key){',
    '    var p=keyMap[key];',
    '    if(p)press(p[0],p[1],pressTime);',
    '  });',
    '  sleep(Math.max(0,Math.round(item.sleep/playbackSpeed)));',
    '});',
    ''
  ].join('\n');
}

export function editorScoreToSkyStudioJson(
  title: string,
  tokens: EditorToken[],
  intervals: EditorIntervals,
  use21Keys: boolean
): string {
  const names = use21Keys ? NOTE_NAMES_21 : NOTE_NAMES_15;
  let time = 0;
  const songNotes: Array<{ time: number; key: string }> = [];
  tokens.forEach((token) => {
    token.notes.forEach((note) => {
      const index = names.indexOf(note as never);
      if (index >= 0) songNotes.push({ time, key: `1Key${index}` });
    });
    time += token.interval;
  });
  const bpm = Math.max(1, Math.round(60_000 / Math.max(1, intervals.short)));
  return JSON.stringify({
    name: safeTitle(title),
    author: '',
    transcribedBy: 'SkyForce Editor',
    isComposed: true,
    bpm,
    bitsPerPage: 16,
    pitchLevel: 0,
    isEncrypted: false,
    keyMode: use21Keys ? 21 : 15,
    songNotes
  });
}

export function skyStudioJsonToEditor(text: string, intervals: EditorIntervals): string {
  let value: unknown = JSON.parse(text.replace(/^\uFEFF/, ''));
  if (Array.isArray(value)) value = value[0];
  if (!value || typeof value !== 'object') throw new Error('JSON 顶层结构无效');
  const object = value as Record<string, unknown>;
  const rows = Array.isArray(object.songNotes) ? object.songNotes : [];
  const timed = new Map<number, string[]>();
  for (const raw of rows) {
    if (!raw || typeof raw !== 'object') continue;
    const row = raw as Record<string, unknown>;
    const time = Math.max(0, Math.round(Number(row.time)));
    const match = String(row.key ?? '').match(/Key(\d+)/);
    if (!Number.isFinite(time) || !match) continue;
    const note = NOTE_NAMES_21[Number(match[1])];
    if (!note) continue;
    if (!timed.has(time)) timed.set(time, []);
    timed.get(time)?.push(note);
  }
  const groups = [...timed.entries()].sort((a, b) => a[0] - b[0]);
  return groups.map(([time, notes], index) => {
    const nextTime = groups[index + 1]?.[0];
    const diff = nextTime == null ? intervals.default : Math.max(0, nextTime - time);
    return `${[...new Set(notes)].join('&')}${nearestSymbol(diff, intervals)}`;
  }).join('');
}

export function stopPlayback(): void {
  playbackTimers.forEach((timer) => window.clearTimeout(timer));
  playbackTimers = [];
}

export function playEditorTokens(
  tokens: EditorToken[],
  soundPack = 'oscillator',
  onProgress?: (index: number) => void
): number {
  stopPlayback();
  const AudioCtor = window.AudioContext || window.webkitAudioContext;
  if (soundPack === 'oscillator') {
    if (!AudioCtor) throw new Error('当前系统不支持音频试听');
    playbackContext ??= new AudioCtor();
  }
  const context = playbackContext;
  let elapsed = 0;
  tokens.forEach((token, index) => {
    const timer = window.setTimeout(() => {
      onProgress?.(index);
      token.notes.forEach((note) => {
        if (soundPack === 'oscillator' && context) {
          playTone(context, note, Math.min(0.7, token.interval / 1000));
        } else {
          const audio = new Audio(`./sound-packs/builtin/${soundPack}/${note}.wav`);
          audio.volume = 0.75;
          void audio.play();
        }
      });
    }, elapsed);
    playbackTimers.push(timer);
    elapsed += token.interval;
  });
  return elapsed;
}

export function buildLocalChords(tokens: EditorToken[], keyRoot: string): ChordPlanItem[] {
  const scale = scaleForKey(keyRoot);
  return tokens.map((token, index) => {
    const root = scale[index % scale.length] ?? 'c';
    const octave = Number(token.notes[0]?.slice(1) ?? 4);
    const triad = chordNotes(root, octave);
    const added = triad.filter((note) => !token.notes.includes(note)).slice(0, Math.max(0, 3 - token.notes.length));
    return {
      sourceNotes: token.notes,
      addedNotes: added,
      chordName: root.toUpperCase() + (index % 3 === 1 ? 'm' : ''),
      symbol: token.symbol
    };
  });
}

export function applyChordPlan(plan: ChordPlanItem[]): string {
  return plan.map((item) =>
    `${[...new Set([...item.sourceNotes, ...item.addedNotes])].slice(0, 3).join('&')}${item.symbol}`
  ).join('');
}

export function renderScoreCanvas(
  canvas: HTMLCanvasElement,
  title: string,
  tokens: EditorToken[]
): void {
  const perLine = 12;
  const rows = Math.max(1, Math.ceil(tokens.length / perLine));
  canvas.width = 1400;
  canvas.height = 260 + rows * 150;
  const context = canvas.getContext('2d');
  if (!context) throw new Error('无法创建图片画布');
  context.fillStyle = '#ffffff';
  context.fillRect(0, 0, canvas.width, canvas.height);
  context.fillStyle = '#151728';
  context.textAlign = 'center';
  context.font = '700 54px "Microsoft YaHei UI"';
  context.fillText(safeTitle(title), canvas.width / 2, 85);
  context.font = '24px "Microsoft YaHei UI"';
  context.fillStyle = '#777c90';
  context.fillText('SkyForce 简谱长图', canvas.width / 2, 125);

  tokens.forEach((token, index) => {
    const row = Math.floor(index / perLine);
    const column = index % perLine;
    const x = 90 + column * 110;
    const y = 230 + row * 150;
    context.fillStyle = '#1d2033';
    context.font = '700 29px Consolas';
    context.fillText(token.notes.map(noteToJianpu).join('·'), x, y);
    context.fillStyle = '#9297aa';
    context.font = '20px Consolas';
    context.fillText(token.symbol, x + 45, y);
    context.strokeStyle = '#e2e4ec';
    context.beginPath();
    context.moveTo(x - 46, y + 34);
    context.lineTo(x + 58, y + 34);
    context.stroke();
  });
  context.fillStyle = '#a0a4b5';
  context.font = '18px "Microsoft YaHei UI"';
  context.fillText(`共 ${tokens.length} 个音符组 · 由 SkyForce 生成`, canvas.width / 2, canvas.height - 42);
}

function playTone(context: AudioContext, note: string, duration: number): void {
  const oscillator = context.createOscillator();
  const gain = context.createGain();
  oscillator.type = 'sine';
  oscillator.frequency.value = noteFrequency(note);
  gain.gain.setValueAtTime(0.001, context.currentTime);
  gain.gain.exponentialRampToValueAtTime(0.16, context.currentTime + 0.02);
  gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + duration);
  oscillator.connect(gain).connect(context.destination);
  oscillator.start();
  oscillator.stop(context.currentTime + duration + 0.03);
}

function noteFrequency(note: string): number {
  const letters: Record<string, number> = { c: 0, d: 2, e: 4, f: 5, g: 7, a: 9, b: 11 };
  const letter = note[0]?.toLowerCase() ?? 'c';
  const octave = Number(note[1] ?? 4);
  const midi = (octave + 1) * 12 + (letters[letter] ?? 0);
  return 440 * 2 ** ((midi - 69) / 12);
}

function scaleForKey(key: string): string[] {
  const order = ['c', 'd', 'e', 'f', 'g', 'a', 'b'];
  const start = Math.max(0, order.indexOf(key.toLowerCase()));
  return [...order.slice(start), ...order.slice(0, start)];
}

function chordNotes(root: string, octave: number): string[] {
  const order = ['c', 'd', 'e', 'f', 'g', 'a', 'b'];
  const index = order.indexOf(root);
  return [0, 2, 4].map((offset) => {
    const absolute = index + offset;
    return `${order[absolute % 7]}${Math.min(6, octave + Math.floor(absolute / 7))}`;
  });
}

function noteToJianpu(note: string): string {
  return ({ c: '1', d: '2', e: '3', f: '4', g: '5', a: '6', b: '7' } as Record<string, string>)[note[0] ?? 'c'] ?? '?';
}

function nearestSymbol(diff: number, intervals: EditorIntervals): '-' | '~' | ',' {
  const choices = [
    { symbol: '-' as const, delta: Math.abs(diff - intervals.default) },
    { symbol: '~' as const, delta: Math.abs(diff - intervals.short) },
    { symbol: ',' as const, delta: Math.abs(diff - intervals.long) }
  ];
  choices.sort((a, b) => a.delta - b.delta);
  return choices[0]?.symbol ?? '-';
}

function normalizeSymbol(value: unknown): '-' | '~' | ',' {
  return value === '~' || value === ',' ? value : '-';
}

function safeTitle(value: string): string {
  return String(value || '未命名乐谱').trim().slice(0, 80) || '未命名乐谱';
}

declare global {
  interface Window {
    webkitAudioContext?: typeof AudioContext;
  }
}
